# Generated by Django 2.2.5 on 2022-09-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_patient_assigneddoctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('General Physician', 'General Physician'), ('NeuroSurgeon', 'NeuroSurgeon'), ('GastroEntologists', 'GastroEntologists'), ('Pediatrician', 'Pediatrician'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='OtherCharge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='doctorFee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='medicineCost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='roomCharge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
